# Generated by Django 4.2 on 2023-04-09 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartobject',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('subcategory__category', 'subcategory'), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
