# Generated by Django 4.2 on 2023-04-05 11:42

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_categories_sub_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(limit_value=Decimal('0.01'), message='Цена не может быть меньше 1 коп')], verbose_name='Цена'),
        ),
    ]
