# Generated by Django 4.2 on 2023-04-07 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={},
        ),
    ]
